### ISSUE TITLE
Question/Request: Xamarin Mobile App

### ISSUE THREAD

**Issue by XceSx6** [TimLariviere/Xamarin-GoogleAuth#2]
Dear Dev,

I know this might be asking for a bit much, but is there any chance you have this Sample available as a Xamarin Mobile App instead of Android and iOS separately ?
This because I do not seem to be getting the desired results while I am working with a Mobile App.
How to code this in the Cross-Platform Xamarin.Forms ?

Some insight into this would be much appreciated.
Keep up the good work, great example !

**Comment by TimLariviere** [comment]
Hi @XceSx6 
Thanks for your interest in this sample. :)

I didn't make the same sample with XF, and I don't think I will.
But I can definitely give you a few pointers on how to migrate this sample to Xamarin.Forms.

Using Xamarin.Auth on XF should be mostly the same as native Xamarin.
What are the problems you encounter?

**Comment by XceSx6** [comment]
Dear Dev,

I'm a bit embarrassed of this, as I am relatively new to Xamarin..
But i can implement the example perfectly in the Android or iOS build Project, but with Xamarin Forms all the design and button definition happens in the main Project. eg: the Sub project Android/iOS have no link or layout defined to the buttons or controls or activities.

So I'm a bit baffled for now as how to:
A) Drop all the code in the main Xamarin Forms project, especially with all the custom code and Interceptor framework
B) Design in the Xamarin.Forms and link activities to the separate Sub projects Coding etc (eg: design Form, put execution code in Android/iOS project ?)
C) .. ?

PS: Your example is the first i bumped into after a few days of trial and error that actually shows all bells and whistles working.
With all the previous I'm getting to authenticating but then it just goes to Google.com :x

Thank you kindly for your contributions, should i get it running in Xamarin.Forms I will let you know :)

**Comment by TimLariviere** [comment]
I have an unreleased Twitter Auth sample, featuring Xamarin.Forms. (not sure it's fully working though)
Maybe this can help you.

The TwitterAuth and Forms folders are what will interest you.
The Native folder is just the same as this repo.

https://github.com/TimLariviere/Sample-XamarinAuth-Twitter

**Comment by XceSx6** [comment]
Well, close, but I'm still going to google.com after logging in.
Seems obvious why, the "GoogleAuthInterceptor.cs" linked to the woodenmouse Uri is in the Android project while the "Auth" var for "MainActivity.Auth?.OnPageLoading(uri_netfx);" is actually in the Forms project on the MainPage.cs 
The Android project has no instance of its parent Forms project and cannot call the OnPageLoading :x
And the Xamarin.Forms projects doesn't know what an Android specific Activity is so, dont rly know how to go about the google.com redirection thing

**Comment by XceSx6** [comment]
Hey @TimLariviere , I'm still not getting back to the App after authentication. It keeps going to google.com
I've added a DependencyService method call back to the Parent OnPageLoading to fix the above problem, but it still doesn't seem to be kicking in. The Twitter example did help me along a bit, but still stuck.
Any idea of what i could be doing wrong ?

**Comment by XceSx6** [comment]
Well my AuthInterceptor isnt firing, and i can't seem to figure out why.
Same setup as with your sample, only my implementation keeps perpetually going to google,com afterwards :(

**Comment by XceSx6** [comment]
You may close this "issue".. It purely had to do with the RedirectUri and registering it properly with Google.
- [https://developers.google.com/identity/protocols/OAuth2InstalledApp](url)
- [https://developers.google.com/identity/protocols/OAuth2InstalledApp#request-parameter-redirect_uri](url)
- [https://support.google.com/cloud/answer/6158849?hl=en#installedapplications&android](url)

I had an key defined for "Other", simply making an Android Specific One fixed the problem.
Define the Debug SHA1 and the Package Name & stuff works right away
